name: Blog Deployment # 이 workflow의 이름

on: [push] # push가 발생할  때 이 workflow를 실행. 특정 브랜치 혹은 특정 파일에 대한 push를 trigger로 설정 가능

jobs:
  build:
    name: Deploying
    runs-on: ubuntu-latest # 가상 환경으로 ubuntu, linux, macOs 등을 설정할 수 있다. 
    steps:
    - name: clone ohseunghyeon.github.io
      uses: actions/checkout@v1
      with:
        repository: ohseunghyeon/ohseunghyeon.github.io
        ref: master

    # - name: clone gatsby- repository
    #   uses: actions/checkout@v1

    # - name: install dependencies
    #   run: yarn

    # - name: gatsby build
    #   run: yarn build

    # - name: check static files
    #   run: ls -al ../ohseunghyeon.github.io

    # - name: empty static file repo
    #   run: rm -rf ../ohseunghyeon.github.io/*
    
    # - run: |
    #     pwd
    #     ls -al ../ohseunghyeon.github.io

    # - name: move build files to static repo
    #   run: mv ./public/* ../ohseunghyeon.github.io
    
    # - name: check static files
    #   run: ls -al ../ohseunghyeon.github.io
    
    - name: cd to static file repo
      run: cd ../ohseunghyeon.github.io

    - run: touch abc

    - name: git status
      run: git status
    - run: git checkout master
    - run: |
        git status
        git log
    
    - name: git commit
      run: |
        git add .
        git commit -m "test"
        git push
        # ls -al
        # pwd
        # cd ..
        # pwd
        # ls -al
        # cd ohseunghyeon.github.io
        # pwd
        # ls -al