name: Blog Deployment # 이 workflow의 이름

on: [push] # push가 발생할  때 이 workflow를 실행. 특정 브랜치 혹은 특정 파일에 대한 push를 trigger로 설정 가능

jobs:
  build:
    name: Deploying
    runs-on: ubuntu-latest # 가상 환경으로 ubuntu, linux, macOs 등을 설정할 수 있다. 
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
