name: Blog Deployment # 이 workflow의 이름

on: [push] # push가 발생할  때 이 workflow를 실행. 특정 브랜치 혹은 특정 파일에 대한 push를 trigger로 설정 가능

jobs:
  build:
    name: Deploying
    runs-on: ubuntu-latest # 가상 환경으로 ubuntu, linux, macOs 등을 설정할 수 있다. 
    steps:
    - name: clone ohseunghyeon.github.io
      run: |
        cd ..
        git clone https://github.com/ohseunghyeon/ohseunghyeon.github.io.git
      # uses: actions/checkout@v1
      # with:
      #   repository: ohseunghyeon/ohseunghyeon.github.io
      #   ref: master
      

    - name: clone gatsby-blog
      uses: actions/checkout@v1

    # - name: install dependencies
    #   run: yarn

    # - name: gatsby build
    #   run: yarn build

    # - name: empty static file repo
    #   run: rm -rf ../ohseunghyeon.github.io/*

    # - name: move build files to static repo
    #   run: mv ./public/* ../ohseunghyeon.github.io

    - name: push changed files
      run: |
        git config --global user.email "postercolo@gmail.com"
        git config --global user.name "ohseunghyeon"
        cd ../ohseunghyeon.github.io
        git checkout master
        touch abc
        git add .
        echo 1
        git commit -m "$(git -C ../gatsby-blog/ log --format=%B -n 1)"
        git remote -v
        echo 2
        git -c http.extraheader="AUTHORIZATION: basic ${{github.token}}" push origin master